{% set name = "lb-nightly-scheduler" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb_nightly_scheduler-{{ version }}.tar.gz
  sha256: 5a326726ec7851b97d3b919427b32ee800873c5afd1b92a80969cc97b16de113

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - gitpython >=3.1.18,<4.0.0
    - lb-nightly-configuration >=0.3,<0.4
    - lb-nightly-db >=0.2,<0.3
    - lb-nightly-rpc >=0.2,<0.3
    - lb-nightly-utils >=0.4.1,<0.5.0
    - luigi >=3.0.3,<4.0.0
    - requests >=2.27.1,<3.0.0

test:
  imports:
    - lb
    - lb.nightly.scheduler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/nightly-builds/lb-nightly-scheduler
  summary: Scheduler implementation for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pikacic
    - maszyman
